[theme]
primaryColor = "#0d6efd"
backgroundColor = "#f0f4f8"
secondaryBackgroundColor = "#ffffff"
textColor = "#262730"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 20

[browser]
gatherUsageStats = false
