[theme]
primaryColor = "#4fc3f7"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
base = "dark"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 20

[browser]
gatherUsageStats = false
